build-nocache: clean
	@docker build --no-cache . -t indexer
	@echo > .main

.main:
	@docker build . -t indexer
	@touch .main

run: .main
	@docker run -it --rm -v %cd%\src:/app indexer python3 main.py

interactive: .main
	@docker run -it --rm -v %cd%\src:/app indexer python3 -i main.py

build: .main

clean:
	-@rm .main
